#!/bin/bash

function cp() { 
  docker cp $2 $(docker-compose ps -q $1):$3
}

docker-compose down
docker-compose up -d
docker-compose exec allinone apt-get update
docker-compose exec allinone apt-get install -y python-apt ca-certificates apt-transport-https sudo ssh
# cp allinone secrets.yaml /etc/secrets.yaml
ansible-playbook -i inventory/allinone quartermaster.yml -c docker -e @secrets.yml -vv 
